config/routes.rb
Rails.application.routes.draw do
  get 'check_in/index'

  get 'check_in/success'

  resources :participants

  resources :locations

  resources :events

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
   has_many :locations
   has_many :participants
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :event
  has_and_belongs_to_many :participants, :autosave => true
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  serialize :visited_locations, Array
  belongs_to :event
  has_and_belongs_to_many :locations, :autosave => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/check_in_controller.rb
class CheckInController < ApplicationController
  def index
    @location = Location_by(tag: params[:tag])
  end

  def success
   @participant = Particpant.find_by(email: params[:email])
   @participant.visited.locations << params[:location_id].to_i
   @participant.save

   respond_to do |format|
     if @participant.save
	format.html { redirect_to participant_path(@participant), notice: 'Participant was successfully checked in.' }
	format.json { render :show, status: :created, location: @participant }
     else 
	format.html { render :new }
	format.json { render json: @participant.errors, status: :unprocessable_entity }
     end
   end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
	@qr = RQRCode::QRCode.new("http://#{request.host}/#{@location.tag}", :size => 8, :level => :q) 
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
	Participant.where(event_id: @location.event_id).each do |p|
	  p.locations << @location
	end
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :tag, :event_id)
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
	Location.where(event_id: @participant.event_id).each do |l|
	   l.participants << @participant
	end
        format.html { redirect_to edit_event_path(@participant.event_id), notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to edit_event_path(@participant.event_id), notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to edit_event_path(@participant.event_id), notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:email, :event_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_in_helper.rb
module CheckInHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/check_in/index.html.erb
<h1>CheckIn#index</h1>
<p>Find me in app/views/check_in/index.html.erb</p>

app/views/check_in/success.html.erb
<h1>CheckIn#success</h1>
<p>Find me in app/views/check_in/success.html.erb</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <h3>Locations</h3>

   <table>
	<thead>
	  <tr>
	     <th>Name</th>
	     <th>Tag</th>
             <th>Event</th>
	     <th colspan="3"></th>
	  </tr>
	</thead>

	<tbody>
	   <% @event.locations.each do |location| %>
	      <tr>
		<td><%= location.name %></td>
		<td><%= location.tag %></td>
		<td><%= location.event %></td>
		<td><%= link_to 'Show', location %></td>
		<td><%= link_to 'Edit', edit_location_path(location) %></td>
		<td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?'} %></td>
	     </tr>
	   <% end %>
	</tbody>
    </table>

<%= link_to 'New Location', new_location_path({:event_id => @event.id})  %>

<br>
<br>

   <h3>Participants</h3>

   <table>
     <thead>
	<tr>
	   <th>Email</th>
	   <th>Event</th>
	   <th colspan="3"></th>
	</tr>
     </thead>

     <tbody>
	<%= @event.participants.each do |participant| %>
	  <tr>
	     <td><%= participant.email %></td>
	     <td><%= participant.event %></td>
	     <td><%= link_to 'Show', participant %></td>
	     <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
	     <td><%= link_to 'Destroy', participant, method: :delete, data: {confirm: 'Are you sure?'} %></td>
	  </tr>
	<% end %>
     </tbody>
   </table>
  <%= link_to 'New Participant', new_participant_path({:event_id => @event.id}) %>

<br>
<br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<h3>Locations</h3>

<table>
   <thead>
     <tr>
	<th>Name</th>
	<th>Tag</th>
	<th>Event</th>
	<th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
     <% @event.locations.each do |location| %>
	<tr>
	   <td><%= location.name %></td>
	   <td><%= location.tag %></td>
	   <td><%= location.event %></td>
	   <td><%= link_to 'Show', location %></td>
	   <td><%= link_to 'Edit', edit_location_path(location) %></td>
	   <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?'} %></td>
	</tr>
     <end>
   </tbody>
</table>

<h3>Participants</h3>

<table>
   <thead>
     <tr>
	<th>Email</th>
	<th>Event</th>
	<th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
     <% @event.participants.each do |participant| %>
	<tr>
	  <td><%= participant.email %></td>
	  <td><%= participant.event %></td>
	  <td><%= link_to 'Show', participant %></td>
	  <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
	  <td><%= link_to 'Destroy', participant, method: :delete, data: {confirm: 'Are you sure?'} %></td>
	</tr>
     <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <%= f.hidden_field :event_id, :value => params[:event_id] : @location.event_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', edit_event_path(@locations.event_id)  %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tag</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.tag %></td>
        <td><%= location.event %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', edit_event_path(params[:event_id])  %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<style type="text/css">

 table {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
}
 td {
   border-width: 0;
   border-style: none;
   border-color: #0000ff;
   border-collapse: collapse;
   padding: 0;
   margin: 0;
   width: 10px;
   height: 10px;
 }
 td.black { background-color: #000; }
 td.white { background-color: #fff; }
</style>

<table>
<% @qr.modules.each_index do |x| %>
  <tr>
  <% @qr.modules.each_index do |y| %>
    <% if @qr.dark?(x,y) %>
      <td class="black"/>
    <% else %>
      <td class="white"/>
    <% end %>
  <% end %>
  </tr>
<% end %>
</table>

<p>
  <strong>Tag:</strong>
  <%= @location.tag %>
</p>

<p>
  <strong>Event:</strong>
  <%= @location.event %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', event_path(@location.event_id)  %>

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Event</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.email %></td>
        <td><%= participant.event_id %></td>
        <td><%= participant.event %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

<p>
  <strong>Event:</strong>
  <%= @participant.event_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @participant.event %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>